### ISSUE TITLE
Farming Simulator 22 (Epic Games Version) Server Setup

### ISSUE THREAD

**Issue by HeyYuvraj** [zaphosting/docs#1250]
### What topic does your proposed suggestion relate to?

Server Setup for Farming Simulator 22 (Epic Games Version)

### How do you aim to structure your proposed change?

Introduction
Pre-Setup Requirements
Installation Steps
Server Configuration
Launching the Server
Connecting to the Server

### Could you briefly summarise the contents you plan to write about to ensure you have the appropriate technical knowledge?

Step-by-step configuration on epic games launcher
Connecting to the Server and managing server

### What is your ZAP ID?

zap480562

### What is your Discord ID?

646310108116287518

### Do you have any previous experience in writing and publishing articles?

Yes, I have written technical guides related to FiveM.

### By submitting this form, you agree that...

- [X] You have read and understood our contribution section on our documentation.
- [X] You understand our guidelines and conditions that exist.
- [X] Your suggestion is original and not a duplicate.
- [X] You have provided the correct ZAP ID.
- [X] You have answered this suggestion form to the best of your ability.
- [X] You agree to receive feedback and communicate with our ZAP docs team.
- [X] You agree to the ZAP-Hosting Contribution Program Terms & Conditions, which can be [accessed here](https://zap-hosting.com/guides/docs/contribution-terms).

**Comment by ThatGuyJacobee** [comment]
Hey there @HeyYuvraj, thank you for your interest in the Contribution Program! 💚

This sounds like a great suggestion especially with the game recently becoming free on Epic Games for a few days. We do already have a guide which covers the traditional setup via their official store, but this seems like an appropriate addition given that there's likely a big influx of people playing via Epic Games. 🙂

Your suggestion is accepted and you can begin writing the guide. Make sure to have a look at our [process and guidelines](https://zap-hosting.com/guides/docs/contribution-guides) guide pages for contributing, to ensure that your content is written to a high standard. 👍

If you have any questions or have a query, don't hesitate to drop a message here and we will be more than happy to help :)
